service: serverless-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  profile: default
  stage: dev
  region: ap-south-1
  role: arn:aws:iam::019590226870:role/serverless-lambda-full

functions:
  FetchDataFunction:
    handler: backend/getdata.getData
    events:
      - httpApi:
          path: /getusers
          method: get
      - httpApi:
          path: /getuser/{empId}
          method: get
          request: 
            parameters: 
                paths: 
                    empId: false
    environment:
      endpoint: testslsdb.cmfm8xjjzbsp.ap-south-1.rds.amazonaws.com
      dbname: testslsdb
      username: subhaslsdb
      dbPassword: thisismytestslsdb123
      tableName: userTable
  SetDataFunction:
    handler: backend/setdata.setData
    events:
      - httpApi:
          path: /setuser
          method: post      
    environment:
      endpoint: testslsdb.cmfm8xjjzbsp.ap-south-1.rds.amazonaws.com
      dbname: testslsdb
      username: subhaslsdb
      dbPassword: thisismytestslsdb123
      tableName: userTable